"""empty message

Revision ID: 60ee5f091a1f
Revises: bf5860382670
Create Date: 2025-07-14 08:37:57.993206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60ee5f091a1f'
down_revision = 'bf5860382670'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('app_settings_pkey'))
    )
    # ### end Alembic commands ###
